### PR TITLE
Murtaza - First draft of Problem Statement.

### PR DESCRIPTION
**Pull request by MurtazaHakimi**
Hello team,
I've uploaded the first draft of problem statement in the README.md file in our Github repository. The problem statement delves into the impact of automation and AI technologies on workforce dynamics across industries. It outlines core questions, global impact, and the goal of our analysis, providing a comprehensive framework for our research. Please review and provide feedback.
_**Note**_: Our documentation will continue to evolve as we progress through the project, becoming more comprehensive and refined over time.
Thank you

### CODE REVIEW

**Comment by MustafaKpn** [comment]
Good job Murtaza. Thanks for adding your questions

**Review by MustafaKpn — COMMENTED** [review]
Nice documentation of the objectives

**Comment by 2024zia** [comment]
Thank you Murtaza!
I appreciate your work on documentation. In process of working on project, we can revies and develop our objectives and goals. 
Regards
Zia

**Comment by 2024zia** [comment]
I confirmed the first draft .

**Pull request merged**
